services:
  api:
    build: ./backend
    ports:
      - "5088:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080

  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start -- --host 0.0.0.0"
    ports:
      - "8080:4200"
    depends_on:
      - api
